server:
  port: 80

spring:
  mvc:
    view:
      suffix: .html
#    web:
#      resources:
#        static-locations: classpath:/templates/


  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smartcampus?useSSL=false&serverTimezone=UTC
      username: root
      password: "123456"

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
